server:
  port: 8002
spring:
  application:
    name: mortal-product-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mortalmall_product
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:com/mortal/mortalmall/mapper/*Mapper.xml

  type-aliases-package: com.mortal.mortalmall.domain,com.mortal.mortalmall.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
